spring:
  application:
    name: Welcome-Service
  boot:
    admin:
      client:
        url: http://localhost:1111/

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'