spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/rams818/Configuration-Properties
          default-label: main

server:
  port: 9099